behaviors:
    PlatformerAgent:
        trainer_type: ppo
        hyperparameters:
            batch_size: 128
            buffer_size: 409600
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
            beta_schedule: linear
            epsilon_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
            goal_conditioning_type: none
            memory:
                sequence_length: 64
                memory_size: 128
            stacked_vectors: 2
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        time_horizon: 128
        max_steps: 5e6
        summary_freq: 10000
        checkpoint_interval: 50000
        keep_checkpoints: 100
        threaded: false
